import { completePreparationGuide, openStratificationTools } from './fixtures/guidedPreparation';
import { expect, test } from './fixtures/isolatedTest';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import readXlsxFile from 'read-excel-file/node';
import { unzipSync } from 'fflate';
import { generateCurrentStratificationRevision } from './stratification-guide-helpers';

test('no-u2 CPT route reaches applicable JTS parameters and output with explicit approximate and no-pressure evidence', async ({ page }, testInfo) => {
  const inputPath = testInfo.outputPath('no-u2-output.csv');
  writeFileSync(inputPath, ['Depth(m),qc(MPa),fs(kPa)', '1.00,6.00,22', '1.50,6.20,23', '2.00,6.40,24'].join('\n'), 'utf8');
  await page.getByTestId('new-project-name').fill('Stage 8 无 u2 闭环'); await page.getByTestId('project-mode-professional').click(); await page.getByTestId('create-project-submit').click(); await page.getByTestId('create-point').click(); await page.getByTestId('point-name-input').fill('CPT-NO-U2-OUTPUT'); await page.getByTestId('confirm-point-command').click(); await page.getByTestId('probe-guide-recommended').click();
  await page.getByTestId('explorer-import').click(); await page.getByTestId('import-file-input').setInputFiles(inputPath);
  await expect(page.getByTestId('import-readiness-dock')).toContainText('CPT 近似（无 u2）');
  await completePreparationGuide(page);
  await page.getByTestId('explorer-project').click(); await page.getByTestId('confirm-jts-probe').click();
  await expect(page.getByTestId('water-depth-input')).toHaveCount(0); await page.getByTestId('confirm-water-context').click();
  await page.getByTestId('explorer-stratification').click(); await openStratificationTools(page); await page.getByTestId('run-jts-classification').click();
  await expect(page.getByTestId('jts-classification-tool')).toContainText('CPT 近似');
  await expect(page.getByTestId('jts-classification-evidence')).toHaveCount(0);
  await expect(page.getByTestId('jts-classification-tool')).toContainText('CPT 近似');
  await expect(page.getByTestId('jts-classification-tool')).not.toContainText('路径不可用');
  await page.getByTestId('apply-jts-classification').click(); await expect(page.getByTestId('stratification-layer-table').locator('button')).toHaveCount(1); await generateCurrentStratificationRevision(page);
  await page.getByTestId('explorer-parameters').click();
  await page.getByTestId('parameter-guide-next').click();
  await page.getByTestId('parameter-guide-next').click();
  await expect(page.getByTestId('parameter-guide-config-phi')).toBeVisible();
  await expect(page.getByTestId('parameter-guide-material-scope')).toHaveValue('unknown');
  await page.getByTestId('parameter-guide-next').click();
  await expect(page.getByTestId('parameter-guide-problem')).toContainText('请确认砂土材料');
  if (process.env.MILESTONE_EVIDENCE === '1') {
    const evidenceDir = path.join(process.cwd(), 'process_logs', 'playwright-mcp', 'parameter-guided-workflow');
    mkdirSync(evidenceDir, { recursive: true });
    await page.setViewportSize({ width: 1440, height: 900 });
    await page.waitForTimeout(300);
    await page.screenshot({ path: path.join(evidenceDir, 'parameter-guide-sand-scope-1440x900.png'), animations: 'disabled' });
    await page.setViewportSize({ width: 1920, height: 1080 });
    await page.waitForTimeout(300);
    await page.screenshot({ path: path.join(evidenceDir, 'parameter-guide-sand-scope-1920x1080.png'), animations: 'disabled' });
  }
  await page.getByTestId('parameter-guide-material-scope').selectOption('within_source');
  await page.getByTestId('parameter-guide-close').click();
  await page.getByTestId('jts-package-material-scope').selectOption('within_source'); await page.getByTestId('run-jts-parameter-package').click();
  await expect(page.getByTestId('jts-parameter-package-evidence')).toContainText('原型成果预检已满足');
  await expect(page.getByTestId('jts-package-checklist')).toContainText('Ch/kh');
  await expect(page.getByTestId('jts-dissipation-not-selected')).toContainText('本次未纳入');
  await page.getByTestId('parameter-confirm-scope').click(); await page.getByTestId('parameter-scope-confirm-submit').click();
  await expect(page.getByTestId('generate-output')).toBeEnabled();
  await page.getByTestId('output-kind').selectOption('excel-workbook');
  const downloads: import('@playwright/test').Download[] = [];
  page.on('download', (download) => downloads.push(download));
  await page.getByTestId('generate-output').click();
  await expect.poll(() => downloads.length).toBe(2);
  const workbookDownload = downloads.find((download) => download.suggestedFilename().endsWith('.xlsx'))!;
  const outputPath = testInfo.outputPath(workbookDownload.suggestedFilename()); await workbookDownload.saveAs(outputPath);
  const workbook = await readXlsxFile(outputPath); const metadata = workbook.find((sheet) => sheet.sheet === '元数据')?.data ?? []; const classifications = workbook.find((sheet) => sheet.sheet === '分类结果')?.data ?? []; const measured = workbook.find((sheet) => sheet.sheet === '测量数据')?.data ?? []; const chartMetadata = workbook.find((sheet) => sheet.sheet === '地层图')?.data ?? [];
  expect(metadata.flat().join(' ')).toContain('无 u2 的 CPT 近似路线'); expect(classifications.slice(1).every((row) => row[9] === 'CPT 近似路线')).toBeTruthy(); expect(measured.slice(1).every((row) => row[4] == null)).toBeTruthy(); expect(chartMetadata).toContainEqual(['轨道', 'qc / fs / 地层柱；u2 不可用，未绘制零值曲线']);
  const archive = unzipSync(new Uint8Array(readFileSync(outputPath))); expect(archive['xl/media/stratigraphy.png']).toBeTruthy();
  await page.reload(); await expect(page.getByTestId('output-history')).toContainText('Excel');
});
